
##### Checks run at pull request #####
# Check quiz formatting
check-quizzes: no
# Check that urls in the content are not broken
url-checker: no
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: no
# Spell check Rmds and quizzes
spell-check: no
# Style any R code
style-code: no
# Test build the docker image if any docker-relevant files have been changed
docker-test: yes

##### Renderings run upon merge to main branch #####
# Rendering each platform's content
render-bookdown: no
render-leanpub: no
render-coursera: no

# What docker image should be used for rendering?
# The default is jhudsl/course_template:main
rendering-docker-image: 'jhudsl/stats-for-genomics:0.9'
